// Generates packages/sdk/src/generated/*.ts from the vendored OpenAPI snapshots in specs/.
// `--check` regenerates into a temp dir and fails if the checked-in files differ.
// The generated files are never edited by hand: change the spec upstream, run
// `npm run specs:sync`, then `npm run generate`.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const bin = join(root, "node_modules", ".bin", "openapi-typescript");
const outDir = join(root, "packages", "sdk", "src", "generated");

const targets = [
  { spec: "specs/pulse-api.agent-sdk.yaml", out: "pulse-api.ts" },
  { spec: "specs/agent-sessions.yaml", out: "agent-sessions.ts" },
];

const header = (spec) =>
  `// GENERATED by scripts/generate-types.mjs from ${spec}. Do not edit.\n` +
  `// Regenerate with \`npm run generate\`; CI runs \`npm run types:check\`.\n\n`;

const check = process.argv.includes("--check");
const tmp = mkdtempSync(join(tmpdir(), "pulse-agent-sdk-gen-"));
let drift = false;
try {
  for (const { spec, out } of targets) {
    const raw = join(tmp, out);
    execFileSync(bin, [join(root, spec), "-o", raw, "--alphabetize=false", "--default-non-nullable=false"], { stdio: ["ignore", "ignore", "inherit"] });
    const generated = header(spec) + readFileSync(raw, "utf8");
    const dest = join(outDir, out);
    if (check) {
      let current = "";
      try {
        current = readFileSync(dest, "utf8");
      } catch {}
      if (current !== generated) {
        drift = true;
        console.error(`drift: ${dest} does not match ${spec}. Run \`npm run generate\`.`);
      } else {
        console.log(`ok: ${out} matches ${spec}`);
      }
    } else {
      writeFileSync(dest, generated);
      console.log(`wrote ${dest}`);
    }
  }
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
if (drift) process.exit(1);
